### ISSUE TITLE
As a travel Agent, I want to be able to create a new travel package, so that I am able to offer it to my customers.

### ISSUE THREAD

**Issue by PradheepShankarSE** [visnunathan8/The-Innovators---Concordia-Travel-Web-Application#1]
- [x] Design database schema for travel packages. - @SunithaGeorgee 
- [x] Create a form for entering travel package details. - @SunithaGeorgee 
- [x] Implement back-end logic to save the travel package data in the database. - @hannaa12 
- [x] Create a UI component to display the newly created travel package - @visnunathan8

**Comment by SunithaGeorgee** [comment]
All the tasks completed and reviewed
